// Cascade Field Services — Power BI semantic model (TMDL)
//
// This is the model definition in TMDL, the text format that Power BI Project
// (.pbip) files use. It carries the star schema, the relationships, and the
// full DAX measure library. The measures are documented in measures.md, and
// their logic is validated against the data by the harness in validation/.
//
// Tables bind to the CSVs in data/ (or to a warehouse view of the same shape).

model Model
	culture: en-US
	defaultPowerBIDataSourceVersion: powerBI_V3
	discourageImplicitMeasures
	sourceQueryCulture: en-US

/// Date dimension. Marked as the model's date table: dataCategory Time on the
/// table plus isKey on dim_date[date], which is what makes the time
/// intelligence measures resolve.
table dim_date
	dataCategory: Time

	column date_key
		dataType: int64
		summarizeBy: none

	column date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		isKey

	column year
		dataType: int64
		summarizeBy: none

	column quarter
		dataType: int64
		summarizeBy: none

	column month
		dataType: int64
		summarizeBy: none

	column month_name
		dataType: string
		summarizeBy: none

	column week
		dataType: int64
		summarizeBy: none

	column weekday
		dataType: int64
		summarizeBy: none

	column is_weekend
		dataType: int64
		summarizeBy: none

/// Technician dimension.
table dim_technician
	column technician_key
		dataType: int64
		summarizeBy: none
	column name
		dataType: string
		summarizeBy: none
	column region
		dataType: string
		summarizeBy: none
	column team
		dataType: string
		summarizeBy: none
	column hire_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none

/// Service-type dimension.
table dim_service
	column service_key
		dataType: int64
		summarizeBy: none
	column service
		dataType: string
		summarizeBy: none
	column category
		dataType: string
		summarizeBy: none
	column list_price
		dataType: decimal
		formatString: \$#,##0
		summarizeBy: none

/// Customer dimension.
table dim_customer
	column customer_key
		dataType: int64
		summarizeBy: none
	column name
		dataType: string
		summarizeBy: none
	column segment
		dataType: string
		summarizeBy: none
	column city
		dataType: string
		summarizeBy: none

/// Jobs fact. One row per job. Carries the revenue, cost, and quality measures.
table fact_jobs
	column job_key
		dataType: int64
		summarizeBy: none
	column date_key
		dataType: int64
		summarizeBy: none
	column technician_key
		dataType: int64
		summarizeBy: none
	column service_key
		dataType: int64
		summarizeBy: none
	column customer_key
		dataType: int64
		summarizeBy: none
	column status
		dataType: string
		summarizeBy: none
	column first_time_fix
		dataType: int64
		summarizeBy: none
	column duration_min
		dataType: int64
		summarizeBy: none
	column revenue
		dataType: decimal
		summarizeBy: sum
	column cost
		dataType: decimal
		summarizeBy: sum

	measure 'Total Revenue' = SUM(fact_jobs[revenue])
		formatString: \$#,##0

	measure 'Total Cost' = SUM(fact_jobs[cost])
		formatString: \$#,##0

	measure 'Gross Margin' = [Total Revenue] - [Total Cost]
		formatString: \$#,##0

	measure 'Gross Margin %' = DIVIDE([Gross Margin], [Total Revenue])
		formatString: 0.0%

	measure 'Job Count' = COUNTROWS(fact_jobs)
		formatString: #,##0

	measure 'Completed Jobs' = CALCULATE([Job Count], fact_jobs[status] = "Completed")
		formatString: #,##0

	measure 'Canceled Jobs' = CALCULATE([Job Count], fact_jobs[status] = "Canceled")
		formatString: #,##0

	measure 'Cancellation Rate' = DIVIDE([Canceled Jobs], [Job Count])
		formatString: 0.0%

	measure 'Average Ticket' = DIVIDE([Total Revenue], [Completed Jobs])
		formatString: \$#,##0

	measure 'First-Time-Fix Rate' =
			DIVIDE(
				CALCULATE([Completed Jobs], fact_jobs[first_time_fix] = 1),
				[Completed Jobs]
			)
		formatString: 0.0%

	measure 'Average Job Duration' = AVERAGE(fact_jobs[duration_min])
		formatString: #,##0" min"

	measure 'Active Technicians' = DISTINCTCOUNT(fact_jobs[technician_key])
		formatString: #,##0

	measure 'Revenue per Technician' = DIVIDE([Total Revenue], [Active Technicians])
		formatString: \$#,##0

	measure 'Revenue MTD' = TOTALMTD([Total Revenue], dim_date[date])
		formatString: \$#,##0

	measure 'Revenue YTD' = TOTALYTD([Total Revenue], dim_date[date])
		formatString: \$#,##0

	measure 'Revenue Last Month' =
			CALCULATE([Total Revenue], DATEADD(dim_date[date], -1, MONTH))
		formatString: \$#,##0

	measure 'Revenue MoM %' =
			DIVIDE([Total Revenue] - [Revenue Last Month], [Revenue Last Month])
		formatString: 0.0%

	// Average revenue across the distinct calendar months in the current
	// filter context. This is an all-period monthly average, not a trailing
	// window, and month numbers collapse across years.
	measure 'Avg Monthly Revenue' =
			AVERAGEX(
				VALUES(dim_date[month]),
				CALCULATE([Total Revenue])
			)
		formatString: \$#,##0

/// Invoices fact. One row per invoice. Carries the cash and AR measures.
table fact_invoices
	column invoice_key
		dataType: int64
		summarizeBy: none
	column date_key
		dataType: int64
		summarizeBy: none
	column job_key
		dataType: int64
		summarizeBy: none
	column amount
		dataType: decimal
		summarizeBy: sum
	column paid_amount
		dataType: decimal
		summarizeBy: sum
	column status
		dataType: string
		summarizeBy: none

	measure 'Invoiced Amount' = SUM(fact_invoices[amount])
		formatString: \$#,##0

	measure 'Collected' = SUM(fact_invoices[paid_amount])
		formatString: \$#,##0

	measure 'Outstanding AR' = [Invoiced Amount] - [Collected]
		formatString: \$#,##0

	measure 'Collection Rate' = DIVIDE([Collected], [Invoiced Amount])
		formatString: 0.0%

// Relationships. Facts to dimensions with single-direction filtering, plus one
// fact-to-fact bridge (rel_invoices_job) tying each invoice to its job.
relationship rel_jobs_date
	fromColumn: fact_jobs.date_key
	toColumn: dim_date.date_key

relationship rel_jobs_technician
	fromColumn: fact_jobs.technician_key
	toColumn: dim_technician.technician_key

relationship rel_jobs_service
	fromColumn: fact_jobs.service_key
	toColumn: dim_service.service_key

relationship rel_jobs_customer
	fromColumn: fact_jobs.customer_key
	toColumn: dim_customer.customer_key

// dim_date -> fact_invoices has two possible paths once rel_invoices_job exists:
// this direct relationship, and the two-hop path through fact_jobs. Leaving both
// active ties them at equal weight, which the Tabular engine resolves as an
// ambiguous filter path (hard error at query time, not just a modeling smell).
// Keeping the fact-to-fact bridge as the one active path is deliberate: invoice
// date always equals its job's date by construction (see data/generate.py, both
// rows are written from the same loop date), so the direct path is redundant
// data, not a distinct grain. Any future measure that needs to filter
// fact_invoices by dim_date without going through fact_jobs should route through
// USERELATIONSHIP('fact_invoices'[date_key], 'dim_date'[date_key]) rather than
// flipping this back to active.
relationship rel_invoices_date
	fromColumn: fact_invoices.date_key
	toColumn: dim_date.date_key
	isActive: false

relationship rel_invoices_job
	fromColumn: fact_invoices.job_key
	toColumn: fact_jobs.job_key
